### ISSUE TITLE
Cannot find Symbol ShellCallback

### ISSUE THREAD

**Issue by diabl0w** [zacharee/ShizukuHack#1]
Sorry to open an issue here but I'm driving myself nuts. I cloned this repo and your HackAPI repo into the api folder

When trying to build, the api module is getting an error at the `import android.os.shellcallback` cannot find symbol

I've tried every which way of trying to figure out why android-studio is not happy about finding that but i cant figure it out.

Any help?

**Comment by zacharee** [comment]
You probably need https://github.com/Reginer/aosp-android-jar

**Comment by diabl0w** [comment]
> You probably need https://github.com/Reginer/aosp-android-jar

Excellent! Thank you very much, that mostly solved the problem. 2 follow up questions if you don't mind.

The class that was failing to build was under api/ .... the gradle file for api says it should be compiling using sdk 31... however when i replaced the android.jar for just sdk31 i was still getting the same error until i just replaced the android.jar for all sdk versions. is something else perhaps incorrect in my setup?

I think there is an issue with Android studio changing the gradle version because it is saying that `compileSdkVersion` is deperecated.

Second quesiton would be: I definitely don't recall needing to change the android.jar previously, i just used whatever studio downloaded from google servers. do you think that they just rehosted some of these files with the removed functionality since the last time I downloaded them?

**Comment by zacharee** [comment]
As far as I know, ShellCallback has always been a hidden class. I'm not sure why you needed to replace all of the JARs.

`compileSdkVersion` was changed to just `compileSdk`, but both do the same thing.

**Comment by diabl0w** [comment]
> As far as I know, ShellCallback has always been a hidden class. I'm not sure why you needed to replace all of the JARs.
> 
> `compileSdkVersion` was changed to just `compileSdk`, but both do the same thing.

yeah i just ended up adding the compileSdk parameter too, appreciate your help
